"""PIN gate for write actions on a publicly shared dashboard.

The threat model is specific: the page is public, anyone can read it, and only
the owner may log sessions, edit plans or trigger a Garmin sync. That makes the
PIN the only thing between a stranger and the athlete's data, so it gets treated
like a credential rather than a formality.

What this does, and why each part matters:

  * **Never stores the PIN.** Config holds a salted PBKDF2-SHA256 hash
    (`REFRESH_PIN_HASH` + `REFRESH_PIN_SALT`), generated by `scripts/set_pin.py`.
    A leaked config file — or a repo pushed public by accident — does not hand
    over the PIN. A plaintext `REFRESH_PIN` is still accepted for local
    convenience, but `warnings()` complains about it.
  * **Constant-time comparison.** `hmac.compare_digest`, so a timing side channel
    cannot be used to learn the digest byte by byte.
  * **Lockout with exponential backoff, persisted server-side.** A four-digit PIN
    is 10,000 guesses; unlimited attempts means it falls in seconds. Attempts are
    counted in the database, not in session state, so opening a fresh browser tab
    or restarting the app does not reset the counter.
  * **Nothing secret reaches the browser.** The hash, the salt and the attempt
    counter stay server-side; the UI only ever learns "yes" or "no" plus how long
    it is locked out for.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Protocol

PBKDF2_ROUNDS = 240_000
ATTEMPTS_KEY = "pin_attempts"
FREE_ATTEMPTS = 3          # before any delay kicks in
MAX_LOCKOUT_S = 3600.0     # an hour is plenty to make brute force pointless
SESSION_TTL_S = float(os.getenv("PIN_SESSION_TTL", "1800"))  # 30 min unlocked


class AuthStore(Protocol):
    def get_state(self, key: str, default: str | None = None) -> str | None: ...
    def set_state(self, key: str, value: str) -> None: ...


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _same(a: str, b: str) -> bool:
    """Constant-time string comparison that tolerates non-ASCII.

    `hmac.compare_digest` raises TypeError when handed `str` containing any
    non-ASCII character, so a PIN with an accented or non-Latin character would
    crash the comparison instead of returning False. Comparing UTF-8 bytes keeps
    the constant-time property and accepts anything the user can type.
    """
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))


def hash_pin(pin: str, salt: str) -> str:
    """PBKDF2-SHA256. Slow on purpose: it makes offline guessing expensive."""
    return hashlib.pbkdf2_hmac(
        "sha256", pin.encode("utf-8"), bytes.fromhex(salt), PBKDF2_ROUNDS
    ).hex()


def new_salt() -> str:
    return secrets.token_hex(16)


class PinGate:
    """Verifies PINs, and refuses to be guessed at."""

    def __init__(
        self,
        store: AuthStore | None = None,
        pin_hash: str | None = None,
        salt: str | None = None,
        plaintext: str | None = None,
    ) -> None:
        self.store = store
        self.pin_hash = (pin_hash if pin_hash is not None
                         else os.getenv("REFRESH_PIN_HASH", "")).strip()
        self.salt = (salt if salt is not None
                     else os.getenv("REFRESH_PIN_SALT", "")).strip()
        self.plaintext = (plaintext if plaintext is not None
                          else os.getenv("REFRESH_PIN", "")).strip()

    # -- configuration --------------------------------------------------
    @property
    def configured(self) -> bool:
        return bool((self.pin_hash and self.salt) or self.plaintext)

    def warnings(self) -> list[str]:
        out = []
        if not self.configured:
            out.append(
                "No PIN is set, so anyone who can open this page can change your "
                "data. Run `python scripts/set_pin.py` before sharing the link."
            )
        elif self.plaintext and not self.pin_hash:
            out.append(
                "Your PIN is stored as plaintext. Run `python scripts/set_pin.py` "
                "to replace it with a salted hash, so a leaked config file does "
                "not leak the PIN."
            )
        if self.plaintext and len(self.plaintext) < 4:
            out.append("Your PIN is shorter than 4 digits — that is trivially guessed.")
        return out

    # -- lockout state --------------------------------------------------
    def _attempts(self) -> dict[str, Any]:
        if self.store is None:
            return {"failures": 0, "locked_until": None}
        raw = self.store.get_state(ATTEMPTS_KEY)
        if not raw:
            return {"failures": 0, "locked_until": None}
        try:
            data = json.loads(raw)
            return data if isinstance(data, dict) else {"failures": 0, "locked_until": None}
        except json.JSONDecodeError:
            return {"failures": 0, "locked_until": None}

    def _save_attempts(self, data: dict[str, Any]) -> None:
        if self.store is not None:
            self.store.set_state(ATTEMPTS_KEY, json.dumps(data, default=str))

    def lockout_remaining(self) -> float:
        until = self._attempts().get("locked_until")
        if not until:
            return 0.0
        try:
            dt = datetime.fromisoformat(str(until))
        except ValueError:
            return 0.0
        if not dt.tzinfo:
            dt = dt.replace(tzinfo=timezone.utc)
        return max(0.0, (dt - _now()).total_seconds())

    def _register_failure(self) -> None:
        data = self._attempts()
        data["failures"] = int(data.get("failures", 0)) + 1
        over = data["failures"] - FREE_ATTEMPTS
        if over > 0:
            # 5s, 10s, 20s, 40s … capped. Ten guesses already costs minutes.
            delay = min(MAX_LOCKOUT_S, 5.0 * (2 ** (over - 1)))
            data["locked_until"] = (_now() + timedelta(seconds=delay)).isoformat()
        self._save_attempts(data)

    def _clear_failures(self) -> None:
        self._save_attempts({"failures": 0, "locked_until": None})

    # -- the check ------------------------------------------------------
    def verify(self, pin: str) -> tuple[bool, str]:
        """Returns (ok, message). Never reveals anything about the correct PIN."""
        if not self.configured:
            return False, ("No PIN is configured on the server, so changes are "
                           "disabled. Run scripts/set_pin.py.")
        wait = self.lockout_remaining()
        if wait > 0:
            return False, (f"Too many incorrect attempts. Locked for another "
                           f"{wait:.0f}s.")
        pin = (pin or "").strip()
        if not pin:
            return False, "Enter your PIN."

        if self.pin_hash and self.salt:
            ok = _same(hash_pin(pin, self.salt), self.pin_hash)
        else:
            ok = _same(pin, self.plaintext)

        if ok:
            self._clear_failures()
            return True, "Unlocked."
        self._register_failure()
        again = self.lockout_remaining()
        return False, ("Incorrect PIN."
                       + (f" Locked for {again:.0f}s." if again > 0 else ""))


def session_expired(unlocked_at: float | None, now: float) -> bool:
    """Unlocked sessions time out, so a shared screen does not stay open."""
    return unlocked_at is None or (now - unlocked_at) > SESSION_TTL_S
